// Generated by CoffeeScript 1.3.3
var Shader, audio, load_hooks, loading;

audio = require('audio');

loading = require('loading');

Shader = require('webgl/shader');

load_hooks = {
  '\.jpg$|\.jpeg$|\.gif$|\.png': function(buffer, callback) {
    var image;
    image = new Image();
    image.src = getURL(buffer);
    return image.onload = function() {
      return callback(image);
    };
  },
  '\.mpg$|\.ogg$|\.wav$': function(buffer, callback) {
    return audio.decode(buffer, function(result) {
      return callback(result);
    });
  },
  '\.shader$': function(source, callback) {
    return callback(new Shader(gl, source));
  }
};

exports.main = function() {
  var Application, application, container;
  document.oncontextmenu = function() {
    return false;
  };
  window.canvas = $('canvas');
  try {
    window.gl = canvas[0].getContext('experimental-webgl');
    if (!window.gl) {
      window.gl = canvas[0].getContext('webgl');
    }
  } catch (_error) {}
  if (window.gl) {
    gl.getExtension('OES_standard_derivatives');
    Application = require('application').Application;
    application = null;
    loading.show('Loading ...');
    return loader.hooks(load_hooks).mount({
      url: 'assets.pack',
      loaded: function() {
        return application = new Application(window.canvas, window.gl);
      },
      progress: loading.progress
    });
  } else {
    canvas.remove();
    $('#ui').empty();
    container = $('<div></div>').css({
      position: 'absolute',
      width: 300,
      left: '50%',
      top: 50,
      marginLeft: -100
    }).appendTo('#ui');
    container.append('<h1>You dont have WebGL</h1>');
    if ($.browser.msie) {
      container.append('<p>You have Internet Explorer, please install <a href="https://www.google.com/intl/en/chrome/browser/">Google Chrome</a> or <a href="http://www.mozilla.org/en-US/firefox/new/">Firefox</a></p>');
    } else if ($.browser.webkit) {
      container.append('<p>If you use OSX Safari, please <a href="http://www.ikriz.nl/2011/08/23/enable-webgl-in-safari">enable WebGL manually</a>. If you use iOS Safari, you cannot use WebGL. If you use Android, please try <a href="http://www.mozilla.org/en-US/mobile/">Firefox Mobile</a> or <a href="https://play.google.com/store/apps/details?id=com.opera.browser&hl=en">Opera Mobile</a></p>');
    }
    return container.append('<p>Please consult the <a href="http://support.google.com/chrome/bin/answer.py?hl=en&answer=1220892">support pages</a> on how to get WebGL for your machine.</p>');
  }
};
